name: info_label
description: "info_label is a Flutter library that provides customizable components for displaying information."
version: 1.3.0
homepage: https://github.com/JhonaCodes/info_label.git

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  alchemist: ^0.13.0

flutter:
  uses-material-design: true